### ISSUE TITLE
Issue expanding Details

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [sghaskell/rest-storage-passwords-manager#1]
`common.js:26 Uncaught TypeError: Cannot read property 'nodeType' of undefined
    at Function.jQuery.acceptData [as accepts] (common.js:26)
    at Data.key (common.js:26)
    at Data.get (common.js:26)
    at Data.access (common.js:26)
    at Function._data (common.js:26)
    at clearOnClickAndRegister (eval at globalEval (common.js:15), <anonymous>:178:28)
    at renderUpdateUserInTable (eval at globalEval (common.js:15), <anonymous>:1117:9)
    at Object.onExpandRow (eval at globalEval (common.js:15), <anonymous>:432:17)
    at BootstrapTable.trigger (eval at globalEval (common.js:15), <anonymous>:2104:51)
    at HTMLAnchorElement.eval (eval at globalEval (common.js:15), <anonymous>:1892:22)`

I get the above javascript stack trace when attempting to expand the details of a credential.

Does not affect all credentials, just, specific ones.

**Comment by sghaskell** [comment]
Thanks for reporting this @ericmck2000 . Does the UI show any strange behavior when this happens? Are there similarities between the credentials that are affected (app, permissions, sharing)?

**Comment by XtremeOwnageDotCom** [comment]
So, I do notice a oddity.

If I expand the row which is having problems.....

![image](https://user-images.githubusercontent.com/5262735/55826992-c23c3800-5ace-11e9-83e4-dd446d4617cf.png)


However- If i expand the OTHER Row.... 

It is actually showing the data from the first row.

![image](https://user-images.githubusercontent.com/5262735/55827041-e5ff7e00-5ace-11e9-9624-a51817cf2949.png)

**Comment by XtremeOwnageDotCom** [comment]
I will add- the credential is is showing for SA-LdapSearch was in place before I added this app.

**Comment by sghaskell** [comment]
Thanks, @ericmck2000 . That's helpful. Let me do some testing with credentials that were in place before installing the app to see if I can replicate this.

**Comment by XtremeOwnageDotCom** [comment]
One oddity after examining my screenshot closer-

you will notice the app scope is set for "MobileIQ", which is the top row.
The Realm, is set to SA-LDAPSearch, which is the bottom row.
Read / Write users are from the top row's record.

**Comment by sghaskell** [comment]
I can't say for sure what's going on because I don't see the rest of the values in the table from the first screenshot. The `Realm` is a tag used to avoid collision of duplicate credential names. The Realm in your second screenshot aligns correctly with the `default` credential. It's entirely possible that credential lives within the `MobileIQ` app scope but I can't say for sure without seeing the rest of the values in the table.

**Comment by sghaskell** [comment]
I found the glitch. It has to do with using spaces in the credential name. I'll have a look into getting a fix shortly.

<img width="1599" alt="Screen Shot 2019-04-09 at 12 21 46 PM" src="https://user-images.githubusercontent.com/8450537/55828865-36bcaa00-5ac2-11e9-8361-ae8f9aff9df3.png">

In the meantime, you can delete that credential or create a new one using hyphens and/or underscores to denote spaces.

**Comment by XtremeOwnageDotCom** [comment]
Its working, with no other effects then messing with the dashboard. So, I will leave it alone until a fix is rolled out. Thanks for the quick resolution/diagnostic.

**Comment by sghaskell** [comment]
@ericmck2000 - I just released version 1.0.8 on Splunkbase to address the issue. Give it a shot and let me know if it works for you.

**Comment by sghaskell** [comment]
[Fixed](https://github.com/sghaskell/rest-storage-passwords-manager/commit/b2202ab7a949a0c4f7f752d192e55c8ad6e3c016)
