### ISSUE TITLE
Splunk 7.3

### ISSUE THREAD

**Issue by luisfeve** [sghaskell/rest-storage-passwords-manager#2]
Installing on a splunk Ent 7.3 the upload app just issue an error.

There was an error processing the upload.Error during app install: failed to extract app from c:\windows\temp\tmpo5yueq to C:\Program Files\Splunk\var\run\splunk\bundle_tmp\163a025bc5b01662: The directory name is invalid.

**Comment by sghaskell** [comment]
Thanks for reporting @luisfeve. What OS are you running? Could you also tell me how you're installing (UI, CLI, manually extracting)?

**Comment by luisfeve** [comment]
Running on a Windows Server 2016 STD, im trying to install on Web UI... I download a tar.gz file and then using the upload app option. There's no instructions to install.

**Comment by sghaskell** [comment]
That's a valid installation method. It seems more like a Windows issue than anything Splunk related. Is this a standalone search head? You could try manually extracting the tar.gz into `%SPLUNK_HOME%\etc\apps`, restart Splunk and see if that works. You could also try using the CLI by running `%SPLUNK_HOME%\bin\splunk install app <file>`

**Comment by luisfeve** [comment]
It works manually! thanks..

**Comment by sghaskell** [comment]
I just tested installing the app on a fresh 7.3 Linux install and had no issues. I don't have access to Windows Server 2016 to troubleshoot.
